spring.application.name=api
server.port=8080

# Configuración de conexión a MongoDB Atlas
# Clúster: eva-u2-spring | Base de datos: discografica-db
spring.data.mongodb.database=discografica-db
spring.data.mongodb.uri=mongodb+srv://eva2_spring:ArTdOupJ5mtFNA3S@eva-u2-spring.x6rytgg.mongodb.net/discografica-db?appName=eva-u2-spring
